import turtle
import time
turtle.bgcolor("black")
turtle.color("yellow")
turtle.pensize(12)
turtle.left(60)
turtle.circle(100)
turtle.penup()
turtle.color("yellow")
turtle.pensize(10)
turtle.setpos(-40,70)
turtle.pendown()
turtle.circle(5)
turtle.penup()
turtle.color("yellow")
turtle.pensize(10)
turtle.setpos(-130,70)
turtle.pendown()
turtle.circle(5)
turtle.penup()
turtle.color("red")
turtle.pensize(10)
turtle.setpos(-130,10)
turtle.left(240)
turtle.pendown()
turtle.circle(50,120)

time.sleep(5)
